[workspace.lints.rust]
unsafe_code = "forbid"
# useused = "allow"

[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/easy/1_two_sum",
    "crates/easy/58_length_of_last_word",
    "crates/easy/66_plus_one",
    "crates/easy/67_add_binary",
    "crates/easy/69_sqrtx",
]
